import {
  CheckCircle2,
  AlertTriangle,
  RefreshCw,
  RotateCcw,
  ShieldCheck,
  Brain,
  Activity
} from 'lucide-react';
import './ResultCard.css';

function ResultCard({ result, onPredictAgain, onReset }) {
  const {
    prediction,
    prediction_code,
    probability,
    confidence,
    model: modelUsed = 'Random Forest'
  } = result || {};

  const isPositive =
    prediction_code === 1 ||
    (typeof prediction === 'string' &&
      (prediction.toLowerCase().includes('detected') || prediction.toLowerCase().includes('positive')));

  const rawConf = confidence !== undefined && confidence !== null ? confidence : probability;
  const confVal = rawConf !== undefined && rawConf !== null ? Number(rawConf) : null;
  const confPercent =
    confVal !== null
      ? (confVal <= 1.0 && confVal >= 0 ? confVal * 100 : confVal).toFixed(1)
      : null;

  return (
    <div
      className={`result-card ${isPositive ? 'result-card--positive' : 'result-card--negative'}`}
      role="region"
      aria-label="Prediction result"
    >
      {/* Top Banner Badge */}
      <div className="result-top-banner">
        <span className="result-status-dot" />
        <span className="result-status-text font-mono">
          {isPositive ? 'ELEVATED CARDIOVASCULAR RISK DETECTED' : 'NO CARDIOVASCULAR DISEASE DETECTED'}
        </span>
      </div>

      <div className="result-body-grid">
        {/* Left Side: Text Info */}
        <div className="result-main-info">
          <div className="result-model-badge font-mono">
            <Brain size={14} />
            <span>MODEL EVALUATOR:</span>
            <strong>{modelUsed}</strong>
          </div>

          <h2 className="result-headline">
            {isPositive ? 'Cardiovascular Disease Detected' : 'No Cardiovascular Disease Detected'}
          </h2>

          <p className="result-description">
            {isPositive
              ? `The trained ${modelUsed} model analyzed the submitted clinical markers (blood pressure, age, cholesterol, etc.) and classified the profile as positive for target cardiovascular risk factors.`
              : `The trained ${modelUsed} model evaluated the 11 patient health parameters and determined the profile falls within normal clinical limits.`}
          </p>

          <div className="result-outcome-tag font-mono">
            <span>PREDICTION CLASS:</span>
            <strong>{isPositive ? 'Positive (Class 1)' : 'Negative (Class 0)'}</strong>
          </div>
        </div>

        {/* Right Side: Radial Gauge Confidence Meter */}
        {confPercent !== null && (
          <div className="result-gauge-box">
            <div className="gauge-circle-container">
              <svg className="gauge-svg" viewBox="0 0 100 100">
                <circle className="gauge-bg" cx="50" cy="50" r="42" />
                <circle
                  className={`gauge-fill ${isPositive ? 'gauge-fill--warn' : 'gauge-fill--good'}`}
                  cx="50"
                  cy="50"
                  r="42"
                  style={{
                    strokeDasharray: 264,
                    strokeDashoffset: 264 - (264 * Math.min(Math.max(Number(confPercent), 0), 100)) / 100
                  }}
                />
              </svg>
              <div className="gauge-inner-text font-mono">
                <span className="gauge-val">{confPercent}%</span>
                <span className="gauge-lbl">CONFIDENCE</span>
              </div>
            </div>
            <span className="gauge-caption font-mono">MODEL CONFIDENCE</span>
          </div>
        )}
      </div>

      {/* Action Buttons */}
      <div className="result-actions-row">
        <button onClick={onPredictAgain} className="btn btn--primary">
          <RefreshCw size={16} />
          <span>Run Another Prediction</span>
        </button>
        <button onClick={onReset} className="btn btn--outline">
          <RotateCcw size={16} />
          <span>Reset Form</span>
        </button>
      </div>

      {/* Footer Disclaimer */}
      <div className="result-disclaimer font-sans">
        <ShieldCheck size={16} className="disclaimer-shield" />
        <div>
          <strong>Educational Machine Learning Outcome:</strong> This result is generated by an algorithmic model trained on dataset features. Always verify clinical findings with a certified healthcare practitioner.
        </div>
      </div>
    </div>
  );
}

export default ResultCard;
